<?php

namespace Database\Seeders;

use App\Models\Invitation;
use App\Models\Rsvp;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Faker\Factory as Faker;

class UserInvitationRsvpSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = $this->couples();
        $faker = Faker::create('id_ID');

        foreach ($data as $couple) {
            // Generate nama Indonesia secara acak untuk setiap pasangan.
            $groomName = $faker->name('male');
            $brideName = $faker->name('female');

            $groomParts = preg_split('/\s+/', trim($groomName));
            $brideParts = preg_split('/\s+/', trim($brideName));

            $groomNickname = $groomParts[0];
            $brideNickname = $brideParts[0];

            $couple['groom_name'] = $groomName;
            $couple['groom_nickname'] = $groomNickname;
            $couple['groom_father'] = $faker->name('male');
            $couple['groom_mother'] = $faker->name('female');

            $couple['bride_name'] = $brideName;
            $couple['bride_nickname'] = $brideNickname;
            $couple['bride_father'] = $faker->name('male');
            $couple['bride_mother'] = $faker->name('female');

            $couple['email'] = Str::slug($groomNickname . '.' . $brideNickname)
                . '.' . $faker->unique()->numberBetween(1000, 9999)
                . '@example.com';

            foreach ($couple['rsvps'] as &$rsvp) {
                $rsvp['name'] = $faker->firstName();
            }
            unset($rsvp);

            $user = User::create([
                'name' => $couple['groom_nickname'] . ' & ' . $couple['bride_nickname'],
                'email' => $couple['email'],
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'user',
                'avatar' => $couple['avatar'],
            ]);

            $invitation = Invitation::create([
                'user_id' => $user->id,
                'template_id' => 2,
                'slug' => Str::slug($couple['groom_nickname'] . '-' . $couple['bride_nickname']),
                'is_default' => false,
                'status' => 'published',
                'primary_color' => '#0d9488',

                'groom_name' => $couple['groom_name'],
                'groom_nickname' => $couple['groom_nickname'],
                'groom_father_name' => $couple['groom_father'],
                'groom_mother_name' => $couple['groom_mother'],
                'groom_child_order' => $couple['groom_order'],
                'foto_pria' => $couple['groom_photo'],

                'bride_name' => $couple['bride_name'],
                'bride_nickname' => $couple['bride_nickname'],
                'bride_father_name' => $couple['bride_father'],
                'bride_mother_name' => $couple['bride_mother'],
                'bride_child_order' => $couple['bride_order'],
                'foto_wanita' => $couple['bride_photo'],

                'wedding_date' => $couple['wedding_date'],

                'akad_location' => $couple['akad_location'],
                'akad_time' => '08:00',
                'akad_time_end' => '10:00',
                'akad_address' => $couple['akad_address'],

                'resepsi_location' => $couple['resepsi_location'],
                'resepsi_time' => '11:00',
                'resepsi_time_end' => 'Selesai',
                'resepsi_address' => $couple['resepsi_address'],

                'wedding_quote' => 'Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan untukmu agar kamu merasa tentram. (QS. Ar-Rum : 21)',
                'enable_rsvp' => 1,
                'enable_gift' => 1,
                'enable_gallery' => 1,
                'enable_music' => 1,
            ]);

            foreach ($couple['rsvps'] as $rsvp) {
                Rsvp::create([
                    'invitation_id' => $invitation->id,
                    'name' => $rsvp['name'],
                    'message' => $rsvp['message'],
                    'attending' => $rsvp['attending'],
                ]);
            }
        } // <-- Tanda kurung kurawal foreach dipindahkan ke sini
    }

    private function couples(): array
    {
        return [
            [
                'groom_name' => 'Budi Santoso',
                'groom_nickname' => 'Budi',
                'groom_father' => 'Tuan Santoso',
                'groom_mother' => 'Nyonya Santoso',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/agus-groom/640/480',
                'bride_name' => 'Siti Aminah',
                'bride_nickname' => 'Siti',
                'bride_father' => 'Tuan Haji Ahmad',
                'bride_mother' => 'Nyonya Haji Aminah',
                'bride_order' => 'Anak ke-2',
                'bride_photo' => 'https://picsum.photos/seed/siti-bride/640/480',
                'email' => 'budi.siti1@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Arif+Budiman&background=1B2A4A&color=fff',
                'wedding_date' => '2026-12-15',
                'akad_location' => 'Masjid Al-Muttaqin',
                'akad_address' => 'Jl. Merdeka No.1, Jakarta Barat',
                'resepsi_location' => 'Gedung Serbaguna Kemang',
                'resepsi_address' => 'Jl. Kemang Raya No.10, Jakarta Selatan',
                'rsvps' => [
                    ['name' => 'Rina', 'message' => 'Selamat yaaa! Semoga menjadi keluarga yang sakinah, mawaddah, warahmah. Aamiin 🤲✨', 'attending' => true],
                    ['name' => 'Doni', 'message' => 'Selamat bro! Maaf banget belum bisa hadir, lagi ada dinas luar kota 🙏 Cepat dapat momongan ya! 👶🏻', 'attending' => false],
                    ['name' => 'Maya', 'message' => 'Happy Wedding! Semoga lancar sampai hari H dan bahagia selalu selamanya ❤️🎉', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Andi Wijaya',
                'groom_nickname' => 'Andi',
                'groom_father' => 'Tuan Wijaya',
                'groom_mother' => 'Nyonya Wijaya',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/yusuf-groom/640/480',
                'bride_name' => 'Dewi Lestari',
                'bride_nickname' => 'Dewi',
                'bride_father' => 'Tuan Lestari',
                'bride_mother' => 'Nyonya Lestari',
                'bride_order' => 'Anak pertama',
                'bride_photo' => 'https://picsum.photos/seed/sari-bride/640/480',
                'email' => 'andi.dewi2@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Rendi+Wijaya&background=1B2A4A&color=fff',
                'wedding_date' => '2026-11-20',
                'akad_location' => 'Masjid Raya Bandung',
                'akad_address' => 'Jl. Asia Afrika No.8, Bandung',
                'resepsi_location' => 'Hotel Savoy Homann',
                'resepsi_address' => 'Jl. Asia Afrika No.112, Bandung',
                'rsvps' => [
                    ['name' => 'Rudi', 'message' => 'Selamat menempuh hidup baru sahabatku! Insya Allah hadir bawa keluarga 🥂🎊', 'attending' => true],
                    ['name' => 'Sari', 'message' => 'Selamat atas pernikahannya! Mohon maaf belum bisa hadir secara langsung, doa terbaik untuk kalian 💖🙏', 'attending' => false],
                    ['name' => 'Bayu', 'message' => 'Mantap brother! Akhirnya nyusul juga 😎 Selamat ya, semoga langgeng sampai kakek nenek 👵👨‍🦳', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Rizky Ramadhan',
                'groom_nickname' => 'Rizky',
                'groom_father' => 'Tuan Ramadhan',
                'groom_mother' => 'Nyonya Ramadhan',
                'groom_order' => 'Anak ke-2',
                'groom_photo' => 'https://picsum.photos/seed/rian-groom/640/480',
                'bride_name' => 'Putri Ayu',
                'bride_nickname' => 'Putri',
                'bride_father' => 'Tuan Ayub',
                'bride_mother' => 'Nyonya Ayub',
                'bride_order' => 'Anak ke-3',
                'bride_photo' => 'https://picsum.photos/seed/rafi-bride/640/480',
                'email' => 'rizky.putri3@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Aditya+Kurnia&background=1B2A4A&color=fff',
                'wedding_date' => '2026-10-05',
                'akad_location' => 'Masjid Nurul Iman',
                'akad_address' => 'Jl. Sudirman No.5, Surabaya',
                'resepsi_location' => 'Grand City Convention Hall',
                'resepsi_address' => 'Jl. Mayjen Sungkono No.20, Surabaya',
                'rsvps' => [
                    ['name' => 'Hendra', 'message' => 'Selamat ya kawan! Semoga acaranya berjalan lancar dan penuh berkah 🤲💐', 'attending' => true],
                    ['name' => 'Lia', 'message' => 'Happy Wedding kalian berdua! Maaf belum bisa hadir, semoga bahagia selalu ya 🥰✨', 'attending' => false],
                    ['name' => 'Fajar', 'message' => 'Selamat menempuh babak baru dalam kehidupan! Semoga selalu saling melengkapi ❤️🥂', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Dimas Prabowo',
                'groom_nickname' => 'Dimas',
                'groom_father' => 'Tuan Prabowo',
                'groom_mother' => 'Nyonya Prabowo',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/tommy-groom/640/480',
                'bride_name' => 'Anisa Rahma',
                'bride_nickname' => 'Anisa',
                'bride_father' => 'Tuan Rahman',
                'bride_mother' => 'Nyonya Rahman',
                'bride_order' => 'Anak pertama',
                'bride_photo' => 'https://picsum.photos/seed/shinta-bride/640/480',
                'email' => 'dimas.anisa4@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Agus+Prasetyo&background=E8D5A3&color=fff',
                'wedding_date' => '2026-09-10',
                'akad_location' => 'Masjid Istiqlal',
                'akad_address' => 'Jl. Taman Wijaya Kusuma, Yogyakarta',
                'resepsi_location' => 'Gedung Jogja Expo Center',
                'resepsi_address' => 'Jl. Raya Janti No.1, Yogyakarta',
                'rsvps' => [
                    ['name' => 'Galih', 'message' => 'Barakallahu lakuma wa baraka \'alaikuma wa jama\'a bainakuma fii khoir. Selamat ya bro! 🤲🎉', 'attending' => true],
                    ['name' => 'Wulan', 'message' => 'Selamat untuk pernikahan kalian! Maaf tidak bisa hadir karena dalam kondisi kurang fit 🙏 Get well soon for me & happy wedding for you!', 'attending' => false],
                    ['name' => 'Eko', 'message' => 'Selamat Dimas & Anisa! Siap meluncur ke lokasi bersama rombongan 🚗💨🥳', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Fajar Nugroho',
                'groom_nickname' => 'Fajar',
                'groom_father' => 'Tuan Nugroho',
                'groom_mother' => 'Nyonya Nugroho',
                'groom_order' => 'Anak ke-3',
                'groom_photo' => 'https://picsum.photos/seed/agus-groom/640/480',
                'bride_name' => 'Rina Kusuma',
                'bride_nickname' => 'Rina',
                'bride_father' => 'Tuan Kusuma',
                'bride_mother' => 'Nyonya Kusuma',
                'bride_order' => 'Anak ke-2',
                'bride_photo' => 'https://picsum.photos/seed/rina-bride/640/480',
                'email' => 'fajar.rina5@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Yusuf+Hidayat&background=E8D5A3&color=fff',
                'wedding_date' => '2026-08-25',
                'akad_location' => 'Masjid Agung Semarang',
                'akad_address' => 'Jl. Gajah No.1, Semarang',
                'resepsi_location' => 'Hotel Ciputra Semarang',
                'resepsi_address' => 'Jl. WR Supratman No.10, Semarang',
                'rsvps' => [
                    ['name' => 'Arif', 'message' => 'Selamat bahagia ya Fajar & Rina! Semoga senantiasa diberikan kelancaran hingga hari H 💐😊', 'attending' => true],
                    ['name' => 'Dina', 'message' => 'Turut berbahagia! Sayang sekali bentrok dengan acara keluarga, tapi doa kami menyertai kalian 🤲❤️', 'attending' => false],
                    ['name' => 'Agus', 'message' => 'Selamat mengarungi bahtera rumah tangga! Semoga harmonis dan romantis selalu 👩‍❤️‍👨✨', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Hendra Setiawan',
                'groom_nickname' => 'Hendra',
                'groom_father' => 'Tuan Setiawan',
                'groom_mother' => 'Nyonya Setiawan',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/agus-groom/640/480',
                'bride_name' => 'Maya Sari',
                'bride_nickname' => 'Maya',
                'bride_father' => 'Tuan Sari',
                'bride_mother' => 'Nyonya Sari',
                'bride_order' => 'Anak pertama',
                'bride_photo' => 'https://picsum.photos/seed/maya-bride/640/480',
                'email' => 'hendra.maya6@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Doni+Prasetyo&background=E8D5A3&color=fff',
                'wedding_date' => '2026-07-18',
                'akad_location' => 'Masjid Raya Sumatera Barat',
                'akad_address' => 'Jl. Pemuda No.1, Padang',
                'resepsi_location' => 'Grand Inna Muara Padang',
                'resepsi_address' => 'Jl. Mayor Ruslan No.3, Padang',
                'rsvps' => [
                    ['name' => 'Bayu', 'message' => 'Selamat Hendra & Maya! Semoga menjadi pasangan abadi dunia hingga akhirat 🌟🙏', 'attending' => true],
                    ['name' => 'Tika', 'message' => 'Happy Wedding! Maaf belum bisa gabung di resepsi, wish you all the best! 💕🎉', 'attending' => false],
                    ['name' => 'Yudi', 'message' => 'Selamat ya! Siap hadir menikmati hidangan resepsinya hehe 😋👍', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Gilang Pratama',
                'groom_nickname' => 'Gilang',
                'groom_father' => 'Tuan Pratama',
                'groom_mother' => 'Nyonya Pratama',
                'groom_order' => 'Anak ke-2',
                'groom_photo' => 'https://picsum.photos/seed/tommy-groom/640/480',
                'bride_name' => 'Nadia Putri',
                'bride_nickname' => 'Nadia',
                'bride_father' => 'Tuan Putra',
                'bride_mother' => 'Nyonya Putra',
                'bride_order' => 'Anak ke-3',
                'bride_photo' => 'https://picsum.photos/seed/sari-bride/640/480',
                'email' => 'gilang.nadia7@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Hendra+Setiawan&background=1B2A4A&color=fff',
                'wedding_date' => '2026-06-30',
                'akad_location' => 'Masjid Dian Al-Mahri',
                'akad_address' => 'Jl. Kramat Jati, Jakarta Timur',
                'resepsi_location' => 'Grand Sahid Jaya',
                'resepsi_address' => 'Jl. Jenderal Sudirman No.86, Jakarta',
                'rsvps' => [
                    ['name' => 'Rendi', 'message' => 'Selamat menjalani kehidupan yang baru kawan! Sukses dan bahagia selalu 🔥🥳', 'attending' => true],
                    ['name' => 'Vina', 'message' => 'Happy Wedding Nadia & Gilang! Maaf banget bentrok dengan jadwal cuti 🙏 Cepat dapat debay ya! 👶', 'attending' => false],
                    ['name' => 'Dicky', 'message' => 'Selamat menikah! Semoga diberkahi rezeki dan kebahagiaan yang melimpah 🤲✨', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Aditya Kurnia',
                'groom_nickname' => 'Adit',
                'groom_father' => 'Tuan Kurnia',
                'groom_mother' => 'Nyonya Kurnia',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/rian-groom/640/480',
                'bride_name' => 'Laras Wati',
                'bride_nickname' => 'Laras',
                'bride_father' => 'Tuan Wati',
                'bride_mother' => 'Nyonya Wati',
                'bride_order' => 'Anak ke-2',
                'bride_photo' => 'https://picsum.photos/seed/rafi-bride/640/480',
                'email' => 'adit.laras8@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Rendi+Wijaya&background=1B2A4A&color=fff',
                'wedding_date' => '2026-05-12',
                'akad_location' => 'Masjid Ar-Rahman',
                'akad_address' => 'Jl. Gajah Mada No.1, Medan',
                'resepsi_location' => 'Hotel Grand Aston',
                'resepsi_address' => 'Jl. Pemuda No.18, Medan',
                'rsvps' => [
                    ['name' => 'Kevin', 'message' => 'Congrats Adit & Laras! Semoga lancar ijab kabulnya besok 🙌 Doa terbaik dari kami!', 'attending' => true],
                    ['name' => 'Siska', 'message' => 'Selamat menempuh hidup baru! Sayang sekali jarak memisahkan, tapi doa tetap sampai kok 💌🥰', 'attending' => false],
                    ['name' => 'Reza', 'message' => 'Akhirnya berlabuh juga cintanya! Selamat ya bro, siap meluncur ke medan ✈️🎉', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Kevin Saputra',
                'groom_nickname' => 'Kevin',
                'groom_father' => 'Tuan Saputra',
                'groom_mother' => 'Nyonya Saputra',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/agus-groom/640/480',
                'bride_name' => 'Dina Rahayu',
                'bride_nickname' => 'Dina',
                'bride_father' => 'Tuan Rahayu',
                'bride_mother' => 'Nyonya Rahayu',
                'bride_order' => 'Anak pertama',
                'bride_photo' => 'https://picsum.photos/seed/shinta-bride/640/480',
                'email' => 'kevin.dina9@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Aditya+Kurnia&background=1B2A4A&color=fff',
                'wedding_date' => '2026-04-20',
                'akad_location' => 'Masjid Al-Ikhlas',
                'akad_address' => 'Jl. Ahmad Yani No.12, Makassar',
                'resepsi_location' => 'Hotel Sahid Jaya Makassar',
                'resepsi_address' => 'Jl. Penghibur No.1, Makassar',
                'rsvps' => [
                    ['name' => 'Firman', 'message' => 'Selamat menempuh hidup baru Kevin & Dina! Semoga menjadi pasangan yang selalu berbahagia 💖🥂', 'attending' => true],
                    ['name' => 'Indah', 'message' => 'Maaf banget belum bisa hadir karena urusan pekerjaan 🙏 Selamat atas pernikahan kalian ya!', 'attending' => false],
                    ['name' => 'Joko', 'message' => 'Barakallah! Semoga kehidupan rumah tangganya selalu diberkahi Allah SWT 🤲✨', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Rafi Alamsyah',
                'groom_nickname' => 'Rafi',
                'groom_father' => 'Tuan Alamsyah',
                'groom_mother' => 'Nyonya Alamsyah',
                'groom_order' => 'Anak ke-2',
                'groom_photo' => 'https://picsum.photos/seed/rian-groom/640/480',
                'bride_name' => 'Gita Pratiwi',
                'bride_nickname' => 'Gita',
                'bride_father' => 'Tuan Pratiwi',
                'bride_mother' => 'Nyonya Pratiwi',
                'bride_order' => 'Anak ke-3',
                'bride_photo' => 'https://picsum.photos/seed/rina-bride/640/480',
                'email' => 'rafi.gita10@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Agus+Prasetyo&background=E8D5A3&color=fff',
                'wedding_date' => '2026-03-08',
                'akad_location' => 'Masjid Raya Pontianak',
                'akad_address' => 'Jl. Imam Bonjol No.5, Pontianak',
                'resepsi_location' => 'Hotel Mega Wisata',
                'resepsi_address' => 'Jl. Gajah Mada No.25, Pontianak',
                'rsvps' => [
                    ['name' => 'Tonny', 'message' => 'Selamat brother! Semoga pernikahannya penuh cinta dan selalu harmonis 💍✨', 'attending' => true],
                    ['name' => 'Fitri', 'message' => 'Selamat Gita & Rafi! Maaf belum bisa menyempatkan hadir, bahagia selalu ya 💕🏻', 'attending' => false],
                    ['name' => 'Doni', 'message' => 'Selamat ya! Siap meluncur bersama teman-teman seperjuangan 🚗🥳', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Yusuf Hidayat',
                'groom_nickname' => 'Yusuf',
                'groom_father' => 'Tuan Hidayat',
                'groom_mother' => 'Nyonya Hidayat',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/yusuf-groom/640/480',
                'bride_name' => 'Hana Safitri',
                'bride_nickname' => 'Hana',
                'bride_father' => 'Tuan Safitri',
                'bride_mother' => 'Nyonya Safitri',
                'bride_order' => 'Anak pertama',
                'bride_photo' => 'https://picsum.photos/seed/rafi-bride/640/480',
                'email' => 'yusuf.hana11@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Yusuf+Hidayat&background=E8D5A3&color=fff',
                'wedding_date' => '2026-02-14',
                'akad_location' => 'Masjid Al-Mukarramah',
                'akad_address' => 'Jl. Veteran No.3, Malang',
                'resepsi_location' => 'Hotel Pelangi Malang',
                'resepsi_address' => 'Jl. Ijen No.1, Malang',
                'rsvps' => [
                    ['name' => 'Arief', 'message' => 'Selamat atas pernikahannya! Semoga menjadi awal dari perjalanan panjang yang membahagiakan 🥰🥂', 'attending' => true],
                    ['name' => 'Sari', 'message' => 'Turut berbahagia! Maaf tidak bisa hadir langsung, wishing you both a lifetime of happiness! ❤️', 'attending' => false],
                    ['name' => 'Bambang', 'message' => 'Selamat Yusuf & Hana! Semoga acaranya sukses dan berjalan lancar tanpa hambatan 🤲🎉', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Arif Budiman',
                'groom_nickname' => 'Arif',
                'groom_father' => 'Tuan Budiman',
                'groom_mother' => 'Nyonya Budiman',
                'groom_order' => 'Anak ke-2',
                'groom_photo' => 'https://picsum.photos/seed/tommy-groom/640/480',
                'bride_name' => 'Vina Oktaviani',
                'bride_nickname' => 'Vina',
                'bride_father' => 'Tuan Oktaviani',
                'bride_mother' => 'Nyonya Oktaviani',
                'bride_order' => 'Anak ke-3',
                'bride_photo' => 'https://picsum.photos/seed/shinta-bride/640/480',
                'email' => 'arif.vina12@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Arif+Budiman&background=1B2A4A&color=fff',
                'wedding_date' => '2026-01-05',
                'akad_location' => 'Masjid Agung Jawa Tengah',
                'akad_address' => 'Jl. Diponegoro No.1, Solo',
                'resepsi_location' => 'Gedung Pura Pakualaman',
                'resepsi_address' => 'Jl. Alun-Alun Lor No.1, Solo',
                'rsvps' => [
                    ['name' => 'Deni', 'message' => 'Happy wedding Arif & Vina! Semoga cepat dikaruniai momongan yang lucu-lucu 👶🏻✨', 'attending' => true],
                    ['name' => 'Ria', 'message' => 'Selamat ya! Mohon maaf ada keperluan mendadak jadi belum bisa merapat. Doa terbaik untuk kalian! 🙏', 'attending' => false],
                    ['name' => 'Surya', 'message' => 'Selamat bro! Sampai ketemu di resepsi nanti malam 🔥🥳', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Doni Prasetyo',
                'groom_nickname' => 'Doni',
                'groom_father' => 'Tuan Prasetyo',
                'groom_mother' => 'Nyonya Prasetyo',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/agus-groom/640/480',
                'bride_name' => 'Eka Wahyuni',
                'bride_nickname' => 'Eka',
                'bride_father' => 'Tuan Wahyuni',
                'bride_mother' => 'Nyonya Wahyuni',
                'bride_order' => 'Anak pertama',
                'bride_photo' => 'https://picsum.photos/seed/rina-bride/640/480',
                'email' => 'doni.eka13@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Doni+Prasetyo&background=E8D5A3&color=fff',
                'wedding_date' => '2025-12-28',
                'akad_location' => 'Masjid Raya Palembang',
                'akad_address' => 'Jl. Basuki Rahmat No.1, Palembang',
                'resepsi_location' => 'Hotel Novotel Palembang',
                'resepsi_address' => 'Jl. R Sukamto No.1, Palembang',
                'rsvps' => [
                    ['name' => 'Rendi', 'message' => 'Selamat menempuh hidup baru sahabat! Bawa rombongan besar nih siap meramaikan 🚌🎉', 'attending' => true],
                    ['name' => 'Mela', 'message' => 'Selamat ya Doni & Eka! Maaf belum bisa hadir karena tugas luar kota. Semoga bahagia selalu 💕🙏', 'attending' => false],
                    ['name' => 'Fajar', 'message' => 'Selamat atas pernikahan kalian! Semoga sakinah mawaddah warahmah 🤲✨', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Rendi Wijaya',
                'groom_nickname' => 'Rendi',
                'groom_father' => 'Tuan Wijaya',
                'groom_mother' => 'Nyonya Wijaya',
                'groom_order' => 'Anak ke-2',
                'groom_photo' => 'https://picsum.photos/seed/agus-groom/640/480',
                'bride_name' => 'Shinta Dewi',
                'bride_nickname' => 'Shinta',
                'bride_father' => 'Tuan Dewi',
                'bride_mother' => 'Nyonya Dewi',
                'bride_order' => 'Anak ke-2',
                'bride_photo' => 'https://picsum.photos/seed/shinta-bride/640/480',
                'email' => 'rendi.shinta14@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Rendi+Wijaya&background=1B2A4A&color=fff',
                'wedding_date' => '2025-11-15',
                'akad_location' => 'Masjid An-Nur',
                'akad_address' => 'Jl. Pemuda No.8, Pekanbaru',
                'resepsi_location' => 'Grand Preview Hotel Pekanbaru',
                'resepsi_address' => 'Jl. Jenderal Sudirman No.2, Pekanbaru',
                'rsvps' => [
                    ['name' => 'Eko', 'message' => 'Selamat Rendi & Shinta! Langgeng sampai tua dan bahagia selalu ya bro 🥂❤️', 'attending' => true],
                    ['name' => 'Linda', 'message' => 'Happy wedding kalian! Maaf berhalangan hadir, kirim doa terbaik dari jauh 🤲💌', 'attending' => false],
                    ['name' => 'Yusuf', 'message' => 'Selamat! Semoga keluarganya selalu dilimpahi keberkahan dan kebahagiaan 😊✨', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Bagus Hermawan',
                'groom_nickname' => 'Bagus',
                'groom_father' => 'Tuan Hermawan',
                'groom_mother' => 'Nyonya Hermawan',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/tommy-groom/640/480',
                'bride_name' => 'Indah Permata',
                'bride_nickname' => 'Indah',
                'bride_father' => 'Tuan Permata',
                'bride_mother' => 'Nyonya Permata',
                'bride_order' => 'Anak pertama',
                'bride_photo' => 'https://picsum.photos/seed/sari-bride/640/480',
                'email' => 'bagus.indah15@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Agus+Prasetyo&background=E8D5A3&color=fff',
                'wedding_date' => '2025-10-20',
                'akad_location' => 'Masjid Raya Banjarmasin',
                'akad_address' => 'Jl. A. Yani No.1, Banjarmasin',
                'resepsi_location' => 'Hotel Mayang Sari',
                'resepsi_address' => 'Jl. Ahmad Yani No.2, Banjarmasin',
                'rsvps' => [
                    ['name' => 'Rizal', 'message' => 'Selamat menempuh hidup baru Bagus & Indah! Insya Allah hadir bawa istri 💑💐', 'attending' => true],
                    ['name' => 'Wulan', 'message' => 'Selamat ya! Sayang banget posisi lagi cuti di luar kota, wish you a happy marriage! ✨💖', 'attending' => false],
                    ['name' => 'Ahmad', 'message' => 'Selamat! Semoga dilancarkan semua prosesinya dan bahagia selamanya 🤲🎉', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Tommy Gunawan',
                'groom_nickname' => 'Tommy',
                'groom_father' => 'Tuan Gunawan',
                'groom_mother' => 'Nyonya Gunawan',
                'groom_order' => 'Anak ke-3',
                'groom_photo' => 'https://picsum.photos/seed/rian-groom/640/480',
                'bride_name' => 'Sari Indah',
                'bride_nickname' => 'Sari',
                'bride_father' => 'Tuan Indah',
                'bride_mother' => 'Nyonya Indah',
                'bride_order' => 'Anak ke-2',
                'bride_photo' => 'https://picsum.photos/seed/lia-bride/640/480',
                'email' => 'tommy.sari16@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Tommy+Gunawan&background=1B2A4A&color=fff',
                'wedding_date' => '2025-09-05',
                'akad_location' => 'Masjid Raya Pontianak',
                'akad_address' => 'Jl. Sultan Abdurrahman No.1, Pontianak',
                'resepsi_location' => 'Convention Center Pontianak',
                'resepsi_address' => 'Jl. Ahmad Yani No.3, Pontianak',
                'rsvps' => [
                    ['name' => 'Andi', 'message' => 'Selamat Tommy & Sari! Semoga rukun-rukun terus dan cepat dapat momongan 👶🏻🥂', 'attending' => true],
                    ['name' => 'Dewi', 'message' => 'Selamat atas pernikahan kalian! Maaf berhalangan hadir karena ada acara keluarga 🙏❤️', 'attending' => false],
                    ['name' => 'Fitri', 'message' => 'Happy Wedding! Semoga menjadi keluarga yang romantis dan penuh kebahagiaan ✨💐', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Rian Hidayat',
                'groom_nickname' => 'Rian',
                'groom_father' => 'Tuan Hidayat',
                'groom_mother' => 'Nyonya Hidayat',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/rian-groom/640/480',
                'bride_name' => 'Lia Rahayu',
                'bride_nickname' => 'Lia',
                'bride_father' => 'Tuan Rahayu',
                'bride_mother' => 'Nyonya Rahayu',
                'bride_order' => 'Anak pertama',
                'bride_photo' => 'https://picsum.photos/seed/lia-bride/640/480',
                'email' => 'rian.lia17@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Rian+Hidayat&background=E8D5A3&color=fff',
                'wedding_date' => '2025-08-03',
                'akad_location' => 'Masjid Raya Denpasar',
                'akad_address' => 'Jl. Gatot Subroto No.1, Denpasar',
                'resepsi_location' => 'Grand Inna Bali',
                'resepsi_address' => 'Jl. Sahid Raya No.2, Denpasar',
                'rsvps' => [
                    ['name' => 'Wahyu', 'message' => 'Hadir - Semoga menjadi keluarga sakinah', 'attending' => true],
                    ['name' => 'Dewi', 'message' => 'Tidak Hadir - Ada acara lain', 'attending' => false],
                    ['name' => 'Agung', 'message' => 'Belum Konfirmasi - Tunggu info dari calon mempelai', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Wahyu Setiawan',
                'groom_nickname' => 'Wahyu',
                'groom_father' => 'Tuan Setiawan',
                'groom_mother' => 'Nyonya Setiawan',
                'groom_order' => 'Anak ke-2',
                'groom_photo' => 'https://picsum.photos/seed/wahyu-groom/640/480',
                'bride_name' => 'Dewi Lestari',
                'bride_nickname' => 'Dewi',
                'bride_father' => 'Tuan Lestari',
                'bride_mother' => 'Nyonya Lestari',
                'bride_order' => 'Anak ke-2',
                'bride_photo' => 'https://picsum.photos/seed/dewi-lestari-bride/640/480',
                'email' => 'wahyu.dewi18@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Wahyu+Setiawan&background=1B2A4A&color=fff',
                'wedding_date' => '2025-06-21',
                'akad_location' => 'Masjid Al-Muttaqin',
                'akad_address' => 'Jl. MT Haryono No.1, Balikpapan',
                'resepsi_location' => 'Hotel Kartika Plaza',
                'resepsi_address' => 'Jl. Jenderal Sudirman No.3, Balikpapan',
                'rsvps' => [
                    ['name' => 'Budi', 'message' => 'Hadir - Insya Allah hadir', 'attending' => true],
                    ['name' => 'Sari', 'message' => 'Tidak Hadir - Berhalangan', 'attending' => false],
                    ['name' => 'Eko', 'message' => 'Hadir - Akan hadir', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Agus Prasetyo',
                'groom_nickname' => 'Agus',
                'groom_father' => 'Tuan Prasetyo',
                'groom_mother' => 'Nyonya Prasetyo',
                'groom_order' => 'Anak pertama',
                'groom_photo' => 'https://picsum.photos/seed/agus-groom/640/480',
                'bride_name' => 'Rina Sari',
                'bride_nickname' => 'Rina',
                'bride_father' => 'Tuan Sari',
                'bride_mother' => 'Nyonya Sari',
                'bride_order' => 'Anak pertama',
                'bride_photo' => 'https://picsum.photos/seed/rina-bride/640/480',
                'email' => 'agus.rina19@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Agus+Prasetyo&background=E8D5A3&color=fff',
                'wedding_date' => '2025-05-14',
                'akad_location' => 'Masjid Raya Manado',
                'akad_address' => 'Jl. Bethesda No.1, Manado',
                'resepsi_location' => 'Hotel Politeknik Negeri Manado',
                'resepsi_address' => 'Jl. Politeknik No.1, Manado',
                'rsvps' => [
                    ['name' => 'Joko', 'message' => 'Hadir - Semoga lancar', 'attending' => true],
                    ['name' => 'Linda', 'message' => 'Tidak Hadir - Tidak bisa hadir', 'attending' => false],
                    ['name' => 'Doni', 'message' => 'Hadir - Saya akan bawa keluarga', 'attending' => true],
                ],
            ],
            [
                'groom_name' => 'Firman Hidayat',
                'groom_nickname' => 'Firman',
                'groom_father' => 'Tuan Hidayat',
                'groom_mother' => 'Nyonya Hidayat',
                'groom_order' => 'Anak ke-3',
                'groom_photo' => 'https://picsum.photos/seed/firman-groom/640/480',
                'bride_name' => 'Gita Pratiwi',
                'bride_nickname' => 'Gita',
                'bride_father' => 'Tuan Pratiwi',
                'bride_mother' => 'Nyonya Pratiwi',
                'bride_order' => 'Anak ke-3',
                'bride_photo' => 'https://picsum.photos/seed/gita-bride/640/480',
                'email' => 'firman.gita20@example.com',
                'avatar' => 'https://ui-avatars.com/api/?name=Firman+Hidayat&background=E8D5A3&color=fff',
                'wedding_date' => '2025-04-02',
                'akad_location' => 'Masjid Raya Mataram',
                'akad_address' => 'Jl. Langko No.1, Mataram',
                'resepsi_location' => 'Hotel Lombok Raya',
                'resepsi_address' => 'Jl. Pattimura No.2, Mataram',
                'rsvps' => [
                    ['name' => 'Rendra', 'message' => 'Hadir - Selamat dan sukses', 'attending' => true],
                    ['name' => 'Maya', 'message' => 'Tidak Hadir - Berhalangan', 'attending' => false],
                    ['name' => 'Galih', 'message' => 'Belum Konfirmasi - Cek jadwal dulu', 'attending' => true],
                ],
            ],
        ];
    }
}